:stem: latexmath

= Java Programming 평가 시험

**알림**

* 프로젝트를 내려받아 작성합니다.
* 클래스의 일부가 작성된 경우, 에러 처리를 위해 임의 추가된 코드는 삭제 후 작성합니다.
* 주어진 코드에 access modifier나 기타 keyword의 추가, 변경 또는 삭제도 가능합니다.
* 문제의 채점은 JUnit 테스트 결과를 기본으로 합니다.
** 코드 작성을 위한 테스트 코드가 주어지며,
** 구현 코드의 검증은 별도의 테스트 코드로 실행됩니다.
** 테스트에서 오류가 발생할 경우, 점수가 부여되지 않습니다.
* **문제를 끝까지 보고 구현을 시작합니다.**
** 문제중 일부는 하나의 구현으로 여러 문제에 적용될 수도 있습니다.

== 1. 계산기 만들기 (100점)

계산기를 만들려고 합니다.

=== 1-1. 계산기에서 사용할 숫자 클래스를 정의하고 구현합니다. (20점)

계산기에서는 유리수와 정수만 사용 가능하지만, 크기에는 제한을 두지 않습니다.

==== 1-1-1. XNumber class를 구현합니다. (4점)

* 계산기에서 사용할 숫자의 기본이 되는 XNumber class는 아래와 같습니다.

[source,java]
----
package com.nhnacademy.number;

/**
 * 기본 연산(+, -, *, /)이 지원되는 수를 정의합니다.
 */
public abstract class XNumber {
    /**
     * 두 수를 더 합니다.
     * add(op1, op2) => op1 + op2
     *
     * @param operand1 피연산자
     * @param operand2 피연산자
     * @exception NullPointerException 인수로 null이 주어졌습니다.
     * @return
     */
    public static XNumber add(XNumber operand1, XNumber operand2) {
        //...
    }

    /**
     * operand1에서 operand2를 뺍니다.
     * subtract(op1, op2) => op1 - op2
     *
     * @param operand1 피연산자
     * @param operand2 피연산자
     * @exception NullPointerException 인수로 null이 주어졌습니다.
     * @return
     */
    public static XNumber subtract(XNumber operand1, XNumber operand2) {
        //...
    }

    /**
     * operand1와 operand2를 곱합니다.
     * multiply(op1, op2) => op1 * op2
     *
     * @param operand1 피연산자
     * @param operand2 피연산자
     * @exception NullPointerException 인수로 null이 주어졌습니다.
     * @return
     */
    public static XNumber multiply(XNumber operand1, XNumber operand2) {
        //...
    }

    /**
     * operand1을 operand2로 나눕니다.
     * divide(op1, op2) => op1 / op2
     *
     * @param operand1 피연산자
     * @param operand2 피연산자
     * @exception NullPointerException 인수로 null이 주어졌습니다.
     * @return
     */
    public static XNumber divide(XNumber operand1, XNumber operand2) {
        //...
    }

    /**
     * 현재 값에 주어진 값을 더합니다.
     * 현재 값은 변경되지 않고, 계산된 값은 새로운 오브젝트로 생성됩니다.
     * number.add(other) => number + other
     *
     * @param other 피연산자
     * @exception NullPointerException 인수로 null이 주어졌습니다.
     * @return
     */
    public abstract XNumber add(XNumber other);

    /**
     * 현재 값에서 주어진 값을 뺍니다.
     * 현재 값은 변경되지 않고, 계산된 값은 새로운 오브젝트로 생성됩니다.
     * number.subtract(other) => number - other
     *
     * @param other 피연산자
     * @exception NullPointerException 인수로 null이 주어졌습니다.
     * @return
     */
    public abstract XNumber subtract(XNumber other);

    /**
     * 현재 값에 주어진 값을 곱합니다.
     * 현재 값은 변경되지 않고, 계산된 값은 새로운 오브젝트로 생성됩니다.
     * number.multiply(other) => number * other
     *
     * @param other 피연산자
     * @exception NullPointerException 인수로 null이 주어졌습니다.
     * @return
     */
    public abstract XNumber multiply(XNumber other);

    /**
     * 현재 값을 주어진 값으로 나눕니다.
     * 현재 값은 변경되지 않고, 계산된 값은 새로운 오브젝트로 생성됩니다.
     * number.divide(other) => number / other
     *
     * @param other 피연산자
     * @exception NullPointerException  인수로 null이 주어졌습니다.
     * @exception DivideByZeroException 인수가 0으로 나눗셈이 되지 않습니다.
     * @return
     */
    public abstract XNumber divide(XNumber other);
}
----
* link:../src/test/java/com/nhnacademy/set1/number/Test10101_XNumber.java[테스트코드]가 정상 수행되도록 구현합니다.
** XNumber는 XRational과 XInteger를 이용해 확인하므로, 1-1-2, 1-1-3을 완료후 진행하시기 바랍니다.


==== 1-1-2. 유리수 클래스(XRational class)를 정의하고 구현합니다. (9점)

* 정수를 이용해 분수로 표현 가능한 모든 수를 말합니다.
* 수학에서 사용되는 분수 표현을 터미널상에서 출력하거나 입력하기 쉽지 않아, "[분자,분모]"의 형태로 사용합니다.
** a / b => [a,b]
** 1 / 2 => [1,2]
* 4칙 연산(+, -, *, /)을 지원하며, 함수 이름은 아래와 같습니다.
** + : add
** - : subtract
** * : multiply
** / : divide
* long, BigInteger, 문자열 등을 이용하여 유리수 생성 시 초깃값으로 사용할 수 있습니다.
+
[source,java]
----
XRational r1= new XRational(1, -2);
XRational r2= new XRational(BigInteger.valueOf(1),
                            BigInteger.valueOf(-2));
XRational r3= new XRational("[1,-2]");
----
* 생성 시 주어지는 초깃값으로 분모에 음수 사용이 가능합니다. 단, 유리수 오브젝트에서 출력되는 분모는 음수가 될 수 없습니다.
+
[source,java]
----
XRational rational = new XRational(1, -2);
System.out.println("[1,-2] => " + rational);
----
+
[source,console]
----
[1,-2] => [-1,2]
----
* 모든 분수는 기약 분수로 표현이 됩니다.
+
[source,java]
----
XRational rational = new XRational(2, 4);
System.out.println("[2,4] => " + rational);
----
+
[source,console]
----
[2,4] => [1,2]
----
** 생성 시 주어지는 문자열은 기약분수가 아니어도 됩니다.
* 문자열 출력 시, 정수 표현이 가능하면 정수 형태로 출력합니다.
+
[source,java]
----
XRational r1 = new XRational(8, 2);
System.out.println("[8,2] => " + rational);
----
+
[source,console]
----
[8,2] => 4
----
* link:../src/test/java/com/nhnacademy/set1/number/Test10102_XRational.java[테스트코드]가 정상 수행되도록 구현합니다.

==== 1-1-3. 정수 클래스(XInteger class)를 정의하고 구현합니다. (7점)

* 정수도 유리수입니다.
* 정수와 정수의 결과는 정수, 정수와 유리수의 결과는 유리수를 반환합니다.
+
[source,java]
----
XInteger i1 = new XInteger(1);
XInteger i2 = new XInteger(-1);
XRational r1 = new XRational(1,-1);

XNumber n1 = i1.add(i2);
XNumber n2 = i1.multiply(i2);
XNumber n3 = i1.add(r1);

System.out.println("n1은 정수인가요? "
                + (n1 instanceof XInteger)?"예":"아니오");
System.out.println("n2은 정수인가요? "
                + (n2 instanceof XInteger)?"예":"아니오");
System.out.println("n3은 정수인가요? "
                + (n3 instanceof XInteger)?"예":"아니오");
----
+
[source,console]
----
n1은 정수인가요? 예
n2은 정수인가요? 예
n3은 정수인가요? 아니오
----
* link:../src/test/java/com/nhnacademy/set1/number/Test10103_XInteger.java[테스트코드]가 정상 수행되도록 구현합니다.

=== 1-2. 문자열로 주어지는 식을 형태소 단위로 분리합니다. (20점)

문자열로 입력되는 식을 숫자, 연산자 등의 형태소 단위로 분류합니다.

* 형태소는 숫자, 4칙 연산자와 괄호를 지원합니다.
** 유리수 : [1,2], [-1,2], [-1, 2], [-1 , -2]
** 정수 : 1, -1, 112013131310124123123123
** 사칙 연산 : +, -, *, /
** 괄호 : (, )
* 형태소 사이에 공백은 있거나 없을 수 있습니다.
** a+b, a + b, a+ b
* 숫자 표현 시 부호화 숫자 사이 공백은 허용되지 않습니다.
** - 123 : -를 부호가 아닌 연산자로 인식합니다.
* 형태소 분석 후 불필요한 공백은 모두 제거합니다.
** "[1 , -2]" => "[1,-2]"
** "1 +   [1 , -2]" => "1", "+", "[1,-2]"

==== 1-2-1. 간단한 식에 대한 형태소 분석을 확인합니다. (5점)

* 숫자와 기본 연산자에 대해 형태소 분석을 확인합니다.
+
[source,java]
----
Tokenizer tokenizer = new Tokenizer();
List<Token> tokenList = tokenizer.evaluate(expression);

System.out.println(expression);
System.out.println("=> " + Arrays.toString(tokenList.toArray()));
----
+
[source,console]
----
1
=> [1]

1+2
=> [1, +, 2]

1-2*3
=> [1, -, 2, *, 3]

1-[1,2]*3
=> [1, -, [1,2], * 3]
----
* link:../src/test/java/com/nhnacademy/set1/calculator/Test10201_SimpleTokenizer.java[테스트코드]가 정상 수행되도록 구현합니다.

==== 1-2-2. 조금 더 복잡한 식에 대한 형태소 분석을 확인합니다. (5점)

* 기본 분석에 음수 처리, 괄호 및 임의의 위치에 공백이 추가됩니다.
+
[source,console]
----
1+-1
=> [1, +, -1]

1 +(-2* -3)
=> [1, +, (, -2, *, -3, )]
----
* link:../src/test/java/com/nhnacademy/set1/calculator/Test10202_CompositeTokenizer.java[테스트코드]가 정상 수행되도록 구현합니다.

==== 1-2-3. 복잡한 식에 대한 형태소 분석을 확인합니다. (10점)

* 계산을 위한 모든 형태소가 포함되며, 이중 괄호 등 다양한 요소들이 복합적으로 추가됩니다.
+
[source,console]
----
1+[-1,2]*(4/3)
=> [1, +, [-1,2], *, (, 4, /, 3, )]

-3 --2 + ([-2, 5] * [2,-3] - (7 / [ 4, 5]))
=> [-3, -, -2, +, (, [-2,5], *, [2,-3], -, (, 7, /, [4,5], ), )]
----
* link:../src/test/java/com/nhnacademy/set1/calculator/Test10203_AdvancedCompositeTokenizer.java[테스트코드]가 정상 수행되도록 구현합니다.

=== 1-3. 형태소 단위로 분석된 식을 받아 계산을 위한 구문 트리를 만듭니다. (30점)

분석된 형태소를 이용해 연산을 위한 구문 트리를 만들 수 있습니다.

* 트리 자료 구조를 이용해 구성됩니다.

==== 1-3-1. 간단한 식에 대한 구문 트리를 구현합니다. (10점)

* 기본 출력되는 형태는 다음과 같습니다.
+
[source,console]
----
1+2
=> (1 + 2)

1*(2+3)
=> (1 * (2 + 3))
----
* link:../src/test/java/com/nhnacademy/set1/calculator/Test10301_SimpleParser.java[테스트코드]가 정상 수행되도록 구현합니다.

==== 1-3-2. 복잡한 식에 대한 구문 트리를 구현합니다. (10점)

* link:../src/test/java/com/nhnacademy/set1/calculator/Test10302_CompositeParser.java[테스트코드]가 정상 수행되도록 구현합니다.

==== 1-3-3. 출력 형식을 변경할 수 있도록 구현합니다. (10점)

* 동일한 구문 트리에 출력 옵션을 주어 출력 형식을 변경합니다.
+
[source,java]
----
Tokenizer tokenizer = new Tokenizer();
SyntaxTreeParser stp = new SyntaxTreeParser();

Node root = stp.parse(tokenizer.evaluate(expression));

System.out.println(expression);
System.out.println("=> INFIX : " + root.toString(Node.Mode.INFIX));
System.out.println("=> PREFIX : " + root.toString(Node.Mode.PREFIX));
System.out.println("=> POSTFIX : " + root.toString(Node.Mode.POSTFIX));
----
+
[source,console]
----
1+2
=> INFIX : (1 + 2)
=> PREFIX : (+ 1 2)
=> POSTFIX : (1 2 +)

1*(2+3)
=> INFIX : (1 * (2 + 3))
=> PREFIX : (* 1 (+ 2 3))
=> POSTFIX : (1 (2 3 +) *)
----
* link:../src/test/java/com/nhnacademy/set1/calculator/Test10303_PrefixCompositeParser.java[테스트코드]가 정상 수행되도록 구현합니다.

=== 1-4. 구문 트리를 받아서 계산을 수행합니다. (30점)

구문 트리를 이용해 계산을 실행합니다.

* 수식을 문자열로 입력받아 계산합니다.
* 연산 순서는 일반적으로 알고 있는 순서를 따릅니다.

[source, java]
----
Tokenizer tokenizer = new Tokenizer();
SyntaxTreeParser stp = new SyntaxTreeParser();

...

public XNumber evaluate(String expression) {
    return stp.parse(tokenizer.evaluate(expression))
              .evaluate();
}
----

==== 1-4-1. 간단한 식에 대한 연산을 실행합니다. (10점)

* 기본적은 두값의 연산을 수행합니다.

[source,console]
----
3 = 3
1+2 = 3
1-2 = -1
1*2 = 2
256/16 = 16
----
* link:../src/test/java/com/nhnacademy/set1/calculator/Test10401_SimpleCalculator.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.

==== 1-4-2. 복잡한 식에 대한 연산을 실행합니다. (10점)

* 정수, 유리수, 음수 및 괄호까지 다양한 요소들로 구성됩니다.
+
[source,console]
----
-3 * 2 + [23, 5] * [2,3] - (2 / [11,3]) = [-574,165]
-3 --2 + ([-2, 5] * [2,-3] - (7 / [ 4, 5])) = [-569,60]
----
* link:../src/test/java/com/nhnacademy/set1/calculator/Test10402_CompositeCalculator.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.

==== 1-4-3. 새로운 연산자를 추가할 수 있는 확장 가능한 계산기를 구현합니다. (10점)

* "%"를 새로운 나눗셈 연산자로 추가합니다.
+
[source, console]
----
1+[1,1]%2 = [3,2]
----
* link:../src/test/java/com/nhnacademy/set1/calculator/Test10403_ExpandableCalculator.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.

== 2. Socket 통신을 위한 Server를 구현합니다. (30점)

=== 2-1. Server를 구현하고, 실행 후 정상적으로 종료되는지 확인합니다. (5점)

* Server는 Thread를 이용해 구동하거나
+
[source,java]
----
TcpServer server = new TcpServer(1234);
new Thread(server).start();
----
* start 함수를 이용해 직접 구동할 수 있습니다.
+
[source,java]
----
TcpServer server = new TcpServer(1234);
server.start();
----
* link:../src/test/java/com/nhnacademy/set1/net/Test201_TcpServerRunning.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.

=== 2-2. Echo Server를 구현합니다. (5점)

* 문자열로 수신된 데이터를 그대로 돌려 주는 echo server를 구현합니다.
* 2-3, 2-4 계속 연관된 문제이므로, 다음을 확인하고 구현합니다. (2-3, 2-4가 어렵다고 판단될 경우, 2-2 기능만 별도 구현해도 됩니다.)
* link:../src/test/java/com/nhnacademy/set1/net/Test202_EchoServer.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.


=== 2-3. 다중 접속이 가능한 MultiConnectionServer구현합니다. (5점)

* 동시 접속 5개를 지원합니다.
* link:../src/test/java/com/nhnacademy/set1/net/Test203_MultiConnectionServer.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.

=== 2-4. PredicateServer를 구현합니다. (5점)

* 문자열로 전송된 숫자를 받아서 짝수면 "true", 홀수면 "false"를 돌려 줍니다.
* 서버에서는 접속되는 Session마다 별도 Thread가 돌도록 구현하며, 이를 위한 class는 PredicateSession으로 정의합니다.
* link:../src/test/java/com/nhnacademy/set1/net/Test204_PredicateServer.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.

=== 2-5. CalcultorServer를 구현합니다. (10점)

* 문자열로 전송된 수식을 계산해서 결과를 문자열로 돌려 줍니다.
* link:../src/test/java/com/nhnacademy/set1/net/Test205_CalculatorServer.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.

== 3. Flow-based Programming을 위한 구성 요소들을 구현합니다. (30점)

Flow-based programming을 위한 구성 요소들을 구현합니다.
단, 데이터를 포함하고 있는 Message는 Jackson의 JsonNode를 사용합니다.


=== 3-1. FBP의 노드간 데이터 전달을 위한 Pipe class를 구현합니다. (5점)

* Pipe class는 아래와 같은 기능으로 구성됩니다.
+
[source,java]
----

public class Pipe {
    // ...

    public boolean isEmpty() {
        // ...
    }

    public int getCount() {
        // ...
    }

    public void push(JsonNode message) {
        // ...
    }

    public JsonNode poll() {
        // ...
    }
}
----
** isEmpty - 저장된 메시지가 없음을 확인합니다.
** getCount - 저장된 메시지의 개수를 확인합니다.
** push - 메시지를 넣습니다.
** pop - 메시지는 꺼냅니다. 메시지는 넣은 순서대로 꺼낼 수 있습니다.
* link:../src/test/java/com/nhnacademy/set1/fbp/Test301_Pipe.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.

=== 3-2. 메시지처리를 위한 Node class를 구현합니다.(10점)

* Node class는 FBP 노드의 최상위 클래스로서 공동적으로 가져야 할 기능을 정의하고 있습니다.
* Node class 아래와 같은 기능으로 구성됩니다.
+
[source,java]
----
package com.nhnacademy.fbp;

public abstract class Node implements Runnable {
    //...

    protected Node() {
        //...
    }

    public void setInterval(long interval) {
        //...
    }

    public long getInterval() {
        //...
    }

    public boolean isRunning() {
        //...
    }

    public synchronized void stop() {
        //...
    }

    public void preprocess() {
        //...
    }

    public void postprocess() {
        //...
    }

    public abstract void process();

    public void run() {
        //...
    }
}
----
** setInterval - 노드는 일정 시간 간격으로 process를 호출하며, 시간 간격 설정이 가능합니다.
** isRunning - Runnable class로서 실행 중인지 확인합니다.
** stop - 실행 중인 노드를 중지시킵니다.
** preprocess - 내부 초기화 등을 위해 실행 시작 후 1회 호출됩니다.
** preprocess - 내부 자원 해제 등을 위해 종료 후 1회 호출됩니다.
** process - 일정 시간 간격으로 반복 호출됩니다.
* link:../src/test/java/com/nhnacademy/set1/fbp/Test302_Node.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.

=== 3-3. FBP 테스트를 위한 데이터 생성 노드가 필요합니다. 데이터 생성을 위한 SupplierNode를 구현합니다. (5점)

* SupplierNode는 주어진 조건에 맞춰 메시지를 생성하여 다음 노드로 전달하는 일을 수행합니다.
* SupplierNode class는 아래와 같은 기능으로 구성됩니다.
+
[source,java]
----
public class SupplierNode extends Node {
    //...

    public SupplierNode() {
        //...
    }

    public SupplierNode(Supplier<JsonNode> action) {
        //...
    }

    public void setSupplier(Supplier<JsonNode> action) {
        //...
    }

    public void connectOutput(Pipe output) {
        //...
    }

    @Override
    public void process() {
        //...
    }

}
----
** 일정 시간 간격으로 반복적으로 수행할 action을 설정할 수 있습니다.
** action이 설정되지 않거나 output pipe가 연결되지 않은 경우, 메시지는 생성되지 않습니다.
** 생성된 메시지는 output pipe로 전송됩니다.
* link:../src/test/java/com/nhnacademy/set1/fbp/Test303_SupplierNode.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.

=== 3-4. FBP 테스트를 위한 데이터의 최종 처리를 위한 노드가 필요합니다. 데이터 처리를 위한 ConsumerNode를 구현합니다. (5점)

* ConsumerNode는 수신된 메시지를 주어진 과정 수행에 사용합니다.
* ConsumerNode는 별도의 출력이 없습니다.
* ConsumerNode class는 아래와 같은 기능으로 구성됩니다.
+
[source,java]
----
public class ConsumerNode extends Node {
    //...

    public ConsumerNode() {
        //...
    }

    public ConsumerNode(Consumer<JsonNode> action) {
        //...
    }

    public void connectInput(Pipe input) {
        //...
    }

    @Override
    public void process() {
        //...
    }
}
----
* link:../src/test/java/com/nhnacademy/set1/fbp/Test304_ConsumerNode.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.


=== 3-5. 메시지 중 특정 데이터를 포함한 경우에만 처리하는 FilterNode를 구현합니다. (5점)

* FilterNode는 입력으로 들어오는 메시지 중 특정 조건을 만족하는 메시지만 출력으로 보내는 기능을 수행합니다.
* FilterNode class는 아래와 같은 기능으로 구성됩니다.
+
[source, java]
----
public class FilterNode extends Node {
    // ...

    public FilterNode(UnaryOperator<JsonNode> operator) {
        // ...
    }

    public void connectInput(Pipe input) {
        // ...
    }

    public void connectOutput(Pipe output) {
        // ...
    }

    @Override점
    public void process() {
        // ...
    }

    // ...
}
----
* link:../src/test/java/com/nhnacademy/set1/fbp/Test305_FilterNode.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.

== 4. Thread에 관하여 (40점)

=== 4-1. ExecutorService를 이용해 임의 분류하기 (20점)

* ExecutorService를 이용해 일정 개수의 thread pool을 생성합니다.
* Runnable class는 아래와 같이 구성됩니다.
+
[source,java]
----
package com.nhnacademy.thread;
의
public class Counter implements Runnable {
    /**
     * 실행 후 임의의 그룹 카운터를 하나 증가 시킨다.
     */
    @Override
    public void run() {
        // ...
    }

    /**
     * 카운터 그룹을 삭제한다.
     */
    public static void clear() {
        // ...
    }

    /**
     * Counter가 실행된 총횟수를 반환한다.
     * clear 호출시 초기화된다.
     * @return 횟수
     */
    public static int getTotalCount() {
        // ...
    }

    /**
     * 실행된 카운터 결과를 반환한다.
     * Thread pool의 개수에 해당하는 만큼의 카운터 그룹이 생성되고, 총합은 실행된 카운터와 동일해야 한다.
     * @return 카운터 그룹
     */
    public static int[] getCounts() {
        // ...
    }
}
----
** getTotalCount는 실행된 모든 Counter 수의 합니다.
* link:../src/test/java/com/nhnacademy/set1/thread/Test401_ExecutorService.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.

=== 4-2. Waiter 만들기 (20점)

* Waiter는 관리자의 업무 종료 명령(stop)이 오기 전까지는 무한 대기를 합니다.
* 단, 대기 중 손님의 요청(interrupt)이 있으면, 업무를 수행하고 수행 횟수를 저장합니다.
* 업무가 끝나고 나면 몇 번의 호출이 있었는지 확인합니다.

**기본 코드**
[source,java]
----
package com.nhnacademy.thread;

public class Waiter implements Runnable {
    // ...

    /**
     * @param waitingTime 대기 시간(단위 ms)
     */
    public Waiter(long waitingTime) {
        // ...
    }

    /**
     * 대기 중 호출 횟수를 돌려 준다.
     * @return 호출 횟수
     */
    public int getCount() {
        // ...
    }

    /**
     * 대기 종료 명령
     */
    public void stop() {
        // ...
    }

    /**
     * 대기 종료 확인 및 기다림
     */
    public void join() throws InterruptedException {
        // ...
    }

    /**
     * 대기 중 업무
     */
    @Override
    public void run() {
        // ...
    }
}
----
* link:../src/test/java/com/nhnacademy/set1/thread/Tes402_Waiter.java[테스트 코드]를 확인하고, 정상 동작하도록 작성합니다.